ALTER TABLE payment_transaction
    ADD COLUMN IF NOT EXISTS account_number VARCHAR(64),
    ADD COLUMN IF NOT EXISTS account_name VARCHAR(128),
    ADD COLUMN IF NOT EXISTS bin VARCHAR(16),
    ADD COLUMN IF NOT EXISTS bank_name VARCHAR(128),
    ADD COLUMN IF NOT EXISTS description VARCHAR(256);
